import Head from 'next/head'
import { Layout } from '@/components/Layout/Layout'
import { Header } from '@/components/Header/Header'
import { Content } from '@/components/Content/Content'
import { CardList } from '@/components/CardList/CardList'
import { NextPage } from 'next'

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Reddit-mirror</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href="/favicon.png" />
      </Head>
      <Layout>
        <Header />
        <Content>
          <CardList />
        </Content>
      </Layout>
    </>
  )
}


export default HomePage
