import Head from 'next/head'
import { Layout } from '@/components/Layout/Layout'
import { Header } from '@/components/Header/Header'
import { Content } from '@/components/Content/Content'
import { CardList } from '@/components/CardList/CardList'
import { NextPage } from 'next'
import { Modal } from '@/components/ui-components/Modal/Modal'
import { Post } from '@/components/Post/Post'
import { useRouter } from 'next/router'
import { createModuleResolutionCache } from 'typescript'

const HomePage: NextPage = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Reddit-mirror</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href="/favicon.png" />
      </Head>
      <Layout>
        <Header />
        <Content>
          <CardList />
        </Content>
      </Layout>

    {!!router.query.post && (
      <Modal>
        <Post postID={router.query.post as string} forModal={true}/>
      </Modal>
    )}
    </>
  )
}


export default HomePage
