import { NextPage } from "next";
import { Post } from "@/components/Post/Post";
import { useRouter } from "next/router";
import Head from 'next/head'

export const PostPage: NextPage = () => {
  const router = useRouter()
  const { id } = router.query;

  return (
    <>
      <Head>
          <title>Post | {id}</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" type="image/png" href="/favicon.png" />
      </Head>
      <Post postID={id as string}/>
    </>
  )
}

export default PostPage
